# Generated by Django 3.2.2 on 2021-05-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shavarma', '0002_auto_20210520_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionofpoint',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
