# Generated by Django 3.2.2 on 2021-05-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shavarma', '0005_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com',
            field=models.TextField(),
        ),
    ]
