# Generated by Django 3.2.2 on 2021-05-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shavarma', '0006_alter_comment_com'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_comment',
            new_name='id_point',
        ),
    ]
