# Generated by Django 3.2.2 on 2021-05-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shavarma', '0007_rename_id_comment_comment_id_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
