# Generated by Django 3.2.2 on 2021-05-24 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shavarma', '0008_remove_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_point',
            new_name='point',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
