# Generated by Django 3.2.2 on 2021-05-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shavarma', '0011_alter_shavarmamodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionofpoint',
            name='rating',
            field=models.FloatField(default=1),
        ),
    ]
