# Generated by Django 3.2.2 on 2021-06-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shavarma', '0014_auto_20210531_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='shavarmamodel',
            name='map',
            field=models.TextField(blank=True),
        ),
    ]
